### PR TITLE
✨ manage visit categories w/ select

### LINKED ISSUE #385: add ability to update visit activity categories
otherwise charts will be less useful

### PR DESCRIPTION
**Pull request by eliascodes**
fixes #385 

### Changes
- Add select box to activities table to allow changing category
- Display activities sorted by ID
- Move Activity page related components into own directory
- Add "Saving" beat loader on all write events

### Testing Requirements
- [x] Visitor
  - Add new visit activity
    - Check newly added activity has correct category
  - Update category of existing activity
  - Delete activity
  - Loading spinner should be visible on page even in scrolled down

### Release Requirements
- PO approval

### Manual Deployment
- Visitor app

### CODE REVIEW

**Comment by astroash** [comment]
This is not working for me:

category_dropdown_bug

**Comment by eliascodes** [comment]
oops, refactoring bug

**Comment by eliascodes** [comment]
Additional comment:
- [ ] page should tell you it has auto-saved

**Comment by PM-Jake** [comment]
Hey Elias - I'm seeing the spinner when I make a change, but it only flashes up for a second - could we extend the amount of time it is on the screen to 5 seconds?

**Comment by eliascodes** [comment]
Currently the spinner appears only for the amount of time it takes to successfully make the change (i.e. communicate with the server). It disappears as soon as the server confirms the change has been made. Do we really want to artificially extend this?

**Comment by PM-Jake** [comment]
Yeah, if we could - the spinner/saved icon is there for a reassurance for the user and it's not too reassuring if they don't see it. And I suspect some of our users might be on the slower side when it comes to tech usage so a slight artificial extension would be good I think.

**Comment by eliascodes** [comment]
I trialled it locally with 5 seconds but it seemed far too long. I've currently set it to 2 seconds. The hosted link should be updated in the next couple of minutes.

**Comment by PM-Jake** [comment]
Ok thanks – yeah 5 sounded a bit longer when I counted it out, but you can never tell until you see it in action. I’ll check it in 5 and let you know what I think


Jake Moffatt
Product Manager

jake.moffatt@powertochange.org.uk<mailto:jake.moffatt@powertochange.org.uk>
07780 000605

You can read our 2019-2022 Strategy, “Community business at the heart of local change” here<https://www.powertochange.org.uk/news/community-business-heart-local-change-strategy-2019-2022/>

[cid:image001.jpg@01D341B3.1874B710]
The Clarence Centre, 6 St George's Circus London, SE1 6FE
www.powertochange.org.uk<http://www.powertochange.org.uk/>

**Comment by astroash** [comment]
NB: Update base branch to master as these changes are related to activities not charts. Charts and activities changes can be bundled for release if needed.

**Comment by astroash** [comment]
## Manual Review

### Saving Spinner
- [ ] Spinner is inline in the page. This means that it will not be visable if the user is scrolled down to edit an entry at the bottom of the page. Do we want to have a hovering spinner that is fixed to a position on the page?
**Pics for reference**
Current loader:
Screen Shot 2020-01-01 at 12 19 43

Unviewable loader when scrolled down:
Screen Shot 2020-01-01 at 12 12 53

To check with PO

**Comment by PM-Jake** [comment]
Re the spinner position. It should be visible wherever the user makes a change, whether they are at the top or the bottom (as it's no use if the user cant see it!).

**Pull request merged**
