### PR TITLE
🔬 allow onChangeSortBy to return default sort order to address QA defect

### PR DESCRIPTION
**Pull request by eliascodes**
related to #98 

Allow `onChangeSortBy` to return default sort order.

### CODE REVIEW

**Comment by astroash** [comment]
Not working when testing locally

steps:
1. go to time table
2. click sort by month
3. click "activity"
4. 👀 observe activity column is sorting z-a

**Comment by eliascodes** [comment]
I only fixed the activities table. Are we interpreting this defect as relating to _all_ text based fields?

**Comment by astroash** [comment]
Yeah, I think it means that all text columns should default to a-z sorting

**Comment by eliascodes** [comment]
> I think it is meant to be by total hours

Nope, see the user story

**Pull request merged**
