### PR TITLE
♻️ [FEATURE] Volunteer app update

### PR DESCRIPTION
**Pull request by eliascodes**
**DO NOT SQUASH**
**REBASE WHEN MERGING**

### Changes
- See commits

Post-review:
- Move "you haven't added any logs" message 
- Fix datepicker limits for admins
- Change "error" popup to "alert"
- Add postcode field to profile page
- Hide loading spinner when error occurs on editing project name

### Testing Requirements
- [x] Volunteer app
  - Build and release internal testing versions of app for Android/iOS
  - Manual testing recapping testing steps in #288, #292, #293 

#### 1. From #288 
- a. On Login, observe login page has placeholders removed and input boxes enlarged
- b. Login as VOLUNTEER
- c. Observe dashboard has copy changed as per recommendations in #278
- d. Observe "Projects" input moved above "Activities" input on "New Log" and "Edit Log" views
- e. Log out
- f. Observe Twine logo has been removed from register page
- g. Log in as VOLUNTEER_ADMIN
- h. Observe nav bar has the the copy change as per recommendations in #278

#### 2. From #292 
- a. Try to sync logs successfully after having been in offline mode (e.g. by trying to add a log while in airplane mode)

#### 3. From #293 
- a. Register as a new volunteer with an invalid post code (error message)
- b. Register as a new volunteer with a valid post code (success)
- c. Try to enable location reminders in app and check that an alert is displayed telling user to enable location services. Doesn't disappear until "OK" button is pressed

#### 4. From TwinePlatform/twine-app#33
- a. Log in as VOLUNTEER_ADMIN
- b. Attempt to edit a log that was created before the beginning of the current month

### Release Requirements
- PO Approval Required

### Manual Deployment
- Volunteer app
  - Android Play Store
  - iOS App Store
- API

### CODE REVIEW

**Comment by astroash** [comment]
@eliascodes are we ready for this to be packaged up for app store testing?

**Comment by Shanozd** [comment]
**Section 1**

> On Login, observe login page has placeholders removed and input boxes enlarged

Overall fine, I've noted that the login fields get hard to read when trying to select them when the keyboard is visible. Something I'll note. No action required

> Change "your hours" to "you gave..."

text on the app is 'You have given..' rather than 'you gave..'  I personally think the former reads better but just checking if that was agreed

**Section 3**

> a. Register as a new volunteer with an invalid post code (error message)

Pop up is good, I noted that when I forgot to put in an email address when registering a new user however I didn't get an error pop up so seems inconsistent. Should this be fixed now or later?

I also noted that there is no indication on password strength until there is an error. Something we can look at later so no action required.

When registering as a new user the notification bar covers the text saying 'You haven't given time yet'
so it can't be read. Should this be fixed now?

> c. Try to enable location reminders in app and check that an alert is displayed telling user to enable location services. Doesn't disappear until "OK" button is pressed

The pop-up works but indicates that its an 'error', when there wasn't an indication that location services needed to be set in the first place so would it be better as an 'alert' or something softer?

**Section 4**

>a. Log in as VOLUNTEER_ADMIN

This may be an edge case. When logging off as a volunteer, then logging on as a VOLUNTEER_ADMIN all the app screens were blank. I had to shut down the app then start it again, then all the text appeared.

>b. Attempt to edit a log that was created before the beginning of the current month

When editing, the date field defaulted to the beginning of the current month (1st August) rather than the actual date of the log.

**Comment by edwardwptc** [comment]
Section 1: 

All looks good. I prefer "You have given" to "You gave" as Shanaka said. 

Section 2:

Succeeded. 

Section 3:

a. Registered "Arnold Whoever", arnold@thegalaxy.com, with postcode "ZZ63 XZ5" or something to that effect. Filled all other details out. Logged in to a frozen, blank white page. Had to back out and re-log in, but successfully did so. Cannot view postcode as it is not listed on "My Profile". Does the above count as an invalid postcode? It's gibberish and there isn't anywhere it relates to in reality. 
b. Didn't do this because the above succeeded. 
c. Worked correctly, as described.

Section 4:
As per Shanaka "When editing, the date field defaulted to the beginning of the current month (1st August) rather than the actual date of the log."

**Comment by astroash** [comment]
> Does the above count as an invalid postcode?

Postcodes are validated on format rather than live post codes, this covers us if any postcodes in the Uk change or are added. Accepted UK formats are:
- AA9A 9AA
- A9A 9AA 
- A9 9AA 
- A99 9AA 
- AA9 9AA
- AA99 9AA

A = Letter
9 = Number

**Comment by edwardwptc** [comment]
Ok cool, I don't remember exactly what it was, but it probably did pass your validation despite not being "real" but I've understood. Registration works then :)

**Comment by eliascodes** [comment]
@Shanozd 

#### 1

> > Add what time period the dashboard stats are calculated over

> I didn't see this implemented?

There is text beneath the total hours summary that says "...since you started volunteering", which indicates that the main figure is the all-time total. Then there are also break-downs for today, last 7 days and last 30 days.

The alternative would be to give the date of the first log for that user, but I figured it might not be obvious what the meaning of that date was (would volunteers recognise it as their first volunteering date?).

Happy to be advised.

#### 3a.
> Should this be fixed now or later?

I've had a quick look and I think it's better to defer this.

> When registering as a new user the notification bar covers the text saying 'You haven't given time yet' so it can't be read

I can't reproduce this on my Android, which phone are you using, and could you attach a screenshot?

#### 4a.
> This may be an edge case. When logging off as a volunteer, then logging on as a VOLUNTEER_ADMIN

This is indeed an edge case, but I can try to spend a little time looking for a fix. If it takes too long though, I think it should be deferred.

#### 4b.
> When editing, the date field defaulted to the beginning of the current month (1st August) rather than the actual date of the log.

I can't reproduce this locally or on my Android version, will ask @astroash to confirm.

**Comment by Shanozd** [comment]
@eliascodes 

> #### 1
> > > Add what time period the dashboard stats are calculated over
> 
> There is text beneath the total hours summary that says "...since you started volunteering", which indicates that the main figure is the all-time total. Then there are also break-downs for today, last 7 days and last 30 days.

OK, not sure what the design parameters were for this one, so lets go with what is there for now

> #### 3a.
> > Should this be fixed now or later?
> 
> I've had a quick look and I think it's better to defer this.
> 
> > When registering as a new user the notification bar covers the text saying 'You haven't given time yet' so it can't be read
> 
> I can't reproduce this on my Android, which phone are you using, and could you attach a screenshot?

**iphone 6s**

IMG_1012


 #### 4a.
> > This may be an edge case. When logging off as a volunteer, then logging on as a VOLUNTEER_ADMIN
> 
> This is indeed an edge case, but I can try to spend a little time looking for a fix. If it takes too long though, I think it should be deferred.

OK

 #### 4b.
> > When editing, the date field defaulted to the beginning of the current month (1st August) rather than the actual date of the log.
> 
> I can't reproduce this locally or on my Android version, will ask @astroash to confirm.
> 
> **EDIT**: Actually I can reproduce this now, will get on it.

OK

**Comment by eliascodes** [comment]
@Shanozd @edwardwptc An updated version of the app has been released, you should be able to re-test.

I've addressed the things we agreed above. Note though that I was not able to find the issue with the blank app page when switching from a `VOLUNTEER` to a `VOLUNTEER_ADMIN` account.

Also while the datepicker should now work properly when editing a log from a previous month, actually saving the log won't work until the accompanying back-end change is deployed into production (which we'll do at the same time we release the apps).

**Comment by Shanozd** [comment]
I've tested the updates and they work for me on IOS

**Comment by eliascodes** [comment]
@Shanozd do you consider that sufficient for "PO approval" or would you like @edwardwptc to also re-review and confirm the defects are addressed on his side?

**Comment by Shanozd** [comment]
@eliascodes we should check on Android as well so it would be good for @edwardwptc to make sure that the changes have been addressed. If its all ok with him then we can go ahead

**Comment by edwardwptc** [comment]
I've tested the updates and it all looks good for me.
I realise my task was to edit existing logs from prior months, which worked. I'm still, as an admin, not able to create a log with a date before the month we are in. I am presuming, as you said above Elias, that this will be working in due course.

**Comment by Shanozd** [comment]
> I'm still, as an admin, not able to create a log with a date before the month we are in. 
Good pick up @edwardwptc, we'll want to make a note to check after its been deployed.

@eliascodes it approved for release

**Pull request merged**
