### PR TITLE
🐛 cycle through colours on dashboard charts

### PR DESCRIPTION
**Pull request by astroash**
**DO NOT MERGE** - FOR REFERENCE

Dashboard app to be temporarily deployed from here due to current release pipeline constraints #238

Separate PR to be created with tests for master
 
#239

### CODE REVIEW

**Comment by astroash** [comment]
UPDATE: deploying from this branch caused hosted build to fail. Need to investigate to see why this is.

**Comment by eliascodes** [comment]
Doesn't look like the production app has a `BUILDPACK` env variable (and turning `NODE_MODULES_CACHE` off is potentially also necessary).

**Comment by astroash** [comment]
Deployed to prodution

**Comment by eliascodes** [comment]
Do we still need this?

**Comment by astroash** [comment]
Closing as no longer deployed from this branch

**Pull request closed without merging**
